name: CI

on: [push, pull_request]

jobs:
  build:
    name: CentOS 7
    runs-on: ubuntu-latest
    env:
      VERSION: 21.02
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build binary
        run: |
          bash -ex build-in-docker.sh
          tar cfvz 7z-"$VERSION".tar.gz ./7z
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: 7z
          path: |
            7z*.tar.gz

  upload:
    name: Create release and upload artifacts
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: Inspect directory after downloading artifacts
        run: ls -alFR
      - name: Create release and upload artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            wget -q https://github.com/TheAssassin/pyuploadtool/releases/download/continuous/pyuploadtool-x86_64.AppImage
            chmod +x pyuploadtool-x86_64.AppImage
            ./pyuploadtool-x86_64.AppImage **/7z*.tar*
